services:
  postgres:
    image: postgres:16-alpine
    container_name: seceurevents_db
    environment:
      POSTGRES_DB: seceurevents
      POSTGRES_USER: seceurevents
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "seceurevents", "-U", "seceurevents"]
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: {}
